### ISSUE TITLE
Need consensus for type of comparison graph

### ISSUE THREAD

**Issue by ecomerford** [mozilla/mdv2-prototype#39]
@chutten @wlach , Georg and I have been discussing the type of graph we should use for the comparison view. Possibilities include a histogram with a line graph overlaid, or a double line graph to show the comparisons. I'd love input on which you think would be a better visualization for comparing the distribution of two versions for a probe! 

Also @wlach , I don't think I'll be able to complete the graph using pure metrics graphics (correct me if I'm wrong!). Any advice on how to pull in vanilla D3 to add a second graph? 

Thanks!

**Comment by wlach** [comment]
I'd need to know more about what exactly you're planning on showing here to give an informed comment. Can you describe what information/comparison you're trying to convey (or link to a reference)? Ideally we would be showing the information that engineers/managers need to understand to make a decision/judgement about what happened, rather than just displaying whatever internal model we have of the data. Less is more here.

metricsgraphics can happily display multiple lines but, yes, showing a histogram and a line in the same visualization might be a non-starter. If metricsgraphics isn't up to the task, I'd recommend looking at using another library: a few people have recommended chart.js to me and it does seem rather nice. Using raw d3 is likely to be painful.

http://www.chartjs.org/

**Comment by ecomerford** [comment]
Thanks for your help! The comparison view is meant to display the [distribution view](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2018-08-19&keys=__none__!__none__!__none__&max_channel_version=nightly%252F63&measure=GC_MS&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2018-06-25&table=0&trim=1&use_submission_date=0) of two different versions for the same probe. 

For example, a user can compare time spent running the garbage collector for nightly version 63 versus 62 or 61, etc. If I understand correctly, this view attempts to give users a quick understanding of how the distributions compare, i.e. whether there's been a huge drop in the median or is a long upper tail where there wasn't before, whereas the evolution graph shows more of a timeline of "events". The compare view will have two graphs overlaid for easy comparison; the evolution view is a single line with time stamps to show change over time. Does that help? If not, perhaps @chutten can give a clearer picture based on his knowledge of the data format.

I think at the moment I'm leaning toward a double line graph if only because having two different types of graphs might suggest that the user is looking at two different types of information... but really all that's different between the graphs is the version that they're comparing against.

**Comment by wlach** [comment]
Ok! Makes sense. I agree that combining a line chart with a histogram might be confusing.

Another alternative might be to show one histogram on top of the other (or alongside it). That might be easier to understand, especially if you labeled it as something like "Old distribution of values" and "New distribution of values".

**Comment by ecomerford** [comment]
@wlach thanks for all of your help! We're tentatively trying out two density area graphs, you can take a look at what I've done [here](https://github.com/mozilla/mdv2/pulls). Definitely still room for conversation here, if you're still interested!
